update

diff --git a/open b/open
--- a/open
+++ b/open
@@ -4,164 +4,166 @@
 #
 #
 
-if [ -d "$@" ]; then
-    ncd "$@"
-elif [ -e "$@" ]; then
-    mime_type=$(file -L -b --mime-type "$@")
-    # the order is important, e.g. foo/bar must appear before foo/*
-    case $mime_type in
-        inode/x-empty)
-            editor "$@"
-            ;;
-        video/*|application/vnd.rn-realmedia)
-            video_player "$@"
-            ;;
-        audio/*)
-            audio_player "$@"
-            ;;
-        image/vnd.djvu)
-            document_reader "$@"
-            ;;
-        image/x-canon-cr2)
-            dcraw -o 1 -w -T "$@"
-            ;;
-        image/svg+xml|application/x-shockwave-flash)
-            web_browser "$@"
-            ;;
-        image/x-xcf)
-            gimp "$@"
-            ;;
-        image/*)
-            image_viewer "$@"
-            ;;
-        application/x-lha)
-            lha x "$@"
-            ;;
-        application/postscript)
-            document_reader "$@"
-            ;;
-        application/pdf)
-            document_reader "$@"
-            ;;
-        application/zip)
-            unzip -d "${@%.*}" "$@"
-            ;;
-        application/x-rar)
-            unrar -ad x "$@"
-            ;;
-        application/x-bittorrent)
-            diana_add "$@"
-            ;;
-        application/vnd.ms-opentype|application/x-font-ttf|application/vnd.font-fontforge-sfd)
-            fontforge "$@"
-            ;;
-        text/html)
-            web_browser "$@"
-            ;;
-        text/troff)
-            man -l "$@"
-            ;;
-        *)
-            case "$@" in
-                *.tar.gz|*.tgz)
-                    tar xvzf "$@"
-                    ;;
-                *.tar.xz)
-                    tar xvJf "$@"
-                    ;;
-                *.tar.bz2)
-                    tar xvjf "$@"
-                    ;;
-                *.bz2)
-                    bunzip2 "$@"
-                    ;;
-                *.tar)
-                    tar xvf "$@"
-                    ;;
-                *.gz)
-                    gunzip "$@"
-                    ;;
-                *.ace)
-                    unace x "$@"
-                    ;;
-                *.chm)
-                    xchm "$@"
-                    ;;
-                *.nzb)
-                    nzbget -A "$@"
-                    ;;
-                *.nfo)
-                    editor "$@"
-                    ;;
-                *.pcf|*.bdf)
-                    fontforge "$@"
-                    ;;
-                *.svg)
-                    web_browser "$@"
-                    ;;
-                *.pps|*.PPS|*.ppt|*.PPT)
-                    ppsei "$@"
-                    ;;
-                *.abw)
-                    abiword "$@"
-                    ;;
-                *.rtf|*.doc)
-                    catdoc -w -s cp1252 "$@"
-                    ;;
-                *.xls)
-                    xls2csv -s cp1252 "$@"
-                    ;;
-                *.xpm)
-                    image_viewer "$@"
-                    ;;
-                *.mp3|*.m3u|*.ogg)
-                    audio_player "$@"
-                    ;;
-                *.mp4|*.avi|*.mpg|*.mpeg|*.mkv|*.ogv|*.f4v|*.m2ts)
-                    video_player "$@"
-                    ;;
-                *.webarchive)
-                    tmp_xml=$(mktemp)
-                    tmp_html=$(mktemp)
-                    plutil -i "$@" -o "$tmp_xml"
-                    webarchive_decodemain "$tmp_xml" > "$tmp_html"
-                    web_browser "$tmp_html"
-                    rm "$tmp_xml"
-                    ;;
-                *.blend)
-                    blender "$@"
-                    ;;
-                *.emulecollection)
-                    amule-emc "$@"
-                    ;;
-                *)
-                    mime_encoding=$(file -L -b --mime-encoding "$@")
-                    case $mime_encoding in
-                        *binary)
-                            xxd -l 128 "$@"
-                            ;;
-                        *)
-                            editor "$@"
-                            ;;
-                    esac
-                    ;;
-            esac
-            ;;
-    esac
-else
-    case "$@" in
-        *://*)
-            web_browser "$@"
-            ;;
-        *:*)
-            handle_uri "$@"
-            ;;
-        *@*.*)
-            mutt "$@"
-            ;;
-        *)
-            echo "file not found: '$@'" >&2
-            exit 1
-            ;;
-    esac
-fi
+while [ $# -gt 0 ] ; do
+    if [ -d "$1" ]; then
+        ncd "$1"
+    elif [ -e "$1" ]; then
+        mime_type=$(file -L -b --mime-type "$1")
+        # the order is important, e.g. foo/bar must appear before foo/*
+        case $mime_type in
+            inode/x-empty)
+                editor "$1"
+                ;;
+            video/*|application/vnd.rn-realmedia)
+                video_player "$1"
+                ;;
+            audio/*)
+                audio_player "$1"
+                ;;
+            image/vnd.djvu)
+                document_reader "$1"
+                ;;
+            image/x-canon-cr2)
+                dcraw -o 1 -w -T "$1"
+                ;;
+            image/svg+xml|application/x-shockwave-flash)
+                web_browser "$1"
+                ;;
+            image/x-xcf)
+                gimp "$1"
+                ;;
+            image/*)
+                image_viewer "$1"
+                ;;
+            application/x-lha)
+                lha x "$1"
+                ;;
+            application/postscript)
+                document_reader "$1"
+                ;;
+            application/pdf)
+                document_reader "$1"
+                ;;
+            application/zip)
+                unzip -d "${@%.*}" "$1"
+                ;;
+            application/x-rar)
+                unrar -ad x "$1"
+                ;;
+            application/x-bittorrent)
+                diana_add "$1"
+                ;;
+            application/vnd.ms-opentype|application/x-font-ttf|application/vnd.font-fontforge-sfd)
+                fontforge "$1"
+                ;;
+            text/html)
+                web_browser "$1"
+                ;;
+            text/troff)
+                man -l "$1"
+                ;;
+            *)
+                case "$1" in
+                    *.tar.gz|*.tgz)
+                        tar xvzf "$1"
+                        ;;
+                    *.tar.xz)
+                        tar xvJf "$1"
+                        ;;
+                    *.tar.bz2)
+                        tar xvjf "$1"
+                        ;;
+                    *.bz2)
+                        bunzip2 "$1"
+                        ;;
+                    *.tar)
+                        tar xvf "$1"
+                        ;;
+                    *.gz)
+                        gunzip "$1"
+                        ;;
+                    *.ace)
+                        unace x "$1"
+                        ;;
+                    *.chm)
+                        xchm "$1"
+                        ;;
+                    *.nzb)
+                        nzbget -A "$1"
+                        ;;
+                    *.nfo)
+                        editor "$1"
+                        ;;
+                    *.pcf|*.bdf)
+                        fontforge "$1"
+                        ;;
+                    *.svg)
+                        web_browser "$1"
+                        ;;
+                    *.pps|*.PPS|*.ppt|*.PPT)
+                        ppsei "$1"
+                        ;;
+                    *.abw)
+                        abiword "$1"
+                        ;;
+                    *.rtf|*.doc)
+                        catdoc -w -s cp1252 "$1"
+                        ;;
+                    *.xls)
+                        xls2csv -s cp1252 "$1"
+                        ;;
+                    *.xpm)
+                        image_viewer "$1"
+                        ;;
+                    *.mp3|*.m3u|*.ogg)
+                        audio_player "$1"
+                        ;;
+                    *.mp4|*.avi|*.mpg|*.mpeg|*.mkv|*.ogv|*.f4v|*.m2ts)
+                        video_player "$1"
+                        ;;
+                    *.webarchive)
+                        tmp_xml=$(mktemp)
+                        tmp_html=$(mktemp)
+                        plutil -i "$1" -o "$tmp_xml"
+                        webarchive_decodemain "$tmp_xml" > "$tmp_html"
+                        web_browser "$tmp_html"
+                        rm "$tmp_xml"
+                        ;;
+                    *.blend)
+                        blender "$1"
+                        ;;
+                    *.emulecollection)
+                        amule-emc "$1"
+                        ;;
+                    *)
+                        mime_encoding=$(file -L -b --mime-encoding "$1")
+                        case $mime_encoding in
+                            *binary)
+                                xxd -l 128 "$1"
+                                ;;
+                            *)
+                                editor "$1"
+                                ;;
+                        esac
+                        ;;
+                esac
+                ;;
+        esac
+    else
+        case "$1" in
+            *://*)
+                web_browser "$1"
+                ;;
+            *:*)
+                handle_uri "$1"
+                ;;
+            *@*.*)
+                mutt "$1"
+                ;;
+            *)
+                echo "file not found: '$1'" >&2
+                ;;
+        esac
+    fi
+    shift
+done
