update

diff --git a/open b/open
--- a/open
+++ b/open
@@ -149,7 +149,7 @@ else
             mutt "$@"
             ;;
         *)
-            echo "don't know how to open '$@'" >&2
+            echo "file not found: '$@'" >&2
             exit 1
             ;;
     esac
