Update

diff --git a/togglethm b/togglethm
--- a/togglethm
+++ b/togglethm
@@ -3,7 +3,7 @@
 current=$(readlink -nse "$XDG_COLORS_DIR/xresources")
 
 if [ $? -eq 1 ] ; then
-    echo "can't find the current color theme" >&2
+    echo "Can't find the current color theme" >&2
     exit 1
 fi
 
